### ISSUE TITLE
$this used in method that should be static

### ISSUE THREAD

**Issue by cortho** [owncloud/user_ldap#486] opened 2019-12-09 11:50 UTC
On owncloud central I found the bug report https://central.owncloud.org/t/owncloud-client-connection-error-503-service-unavailable-propfind-error-using-this-when-not-in-object-context/23222

`{“reqId”:“a328fff6-705c-47bf-a4f8-a903c3bdae8e”,“level”:3,“time”:“2019-12-09T10:26:56+00:00”,“remoteAddr”:“172.17.42.1”,“user”:"–",“app”:“PHP”,“method”:“PROPFIND”,“url”:"/owncloud/remote.php/webdav/",“message”:“Non-static method OCA\User_LDAP\Helper::loginName2UserName() should not be called statically at /var/www/owncloud/lib/private/legacy/hook.php#105”}
{“reqId”:“a328fff6-705c-47bf-a4f8-a903c3bdae8e”,“level”:4,“time”:“2019-12-09T10:26:56+00:00”,“remoteAddr”:“172.17.42.1”,“user”:"–",“app”:“webdav”,“method”:“PROPFIND”,“url”:"/owncloud/remote.php/webdav/",“message”:“Exception: HTTP/1.1 503 Error: Using $this when not in object context: {“Exception”:“Sabre\\DAV\\Exception\\ServiceUnavailable”,“Message”:“Error: Using $this when not in object context”,“Code”:0,“Trace”:”#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(466): Sabre\\Event\\EventEmitter->emit(‘beforeMethod’, Array)\n#3 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/remote.php(70): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(169): handleException(Object(Error))\n#6 {main}",“File”:"\/var\/www\/owncloud\/remote.php",“Line”:68}"}`

After a quick look I found out that the static method was changed to non-static

At https://github.com/owncloud/user_ldap/blob/56e12f08b9d71c47cc51254ae16b54d10bde8aa0/lib/AppInfo/Application.php#L77 loginName2UserName is registered (which is supposed to be static) while at https://github.com/owncloud/user_ldap/blame/56e12f08b9d71c47cc51254ae16b54d10bde8aa0/lib/Helper.php#L199 $this is used.

Before the last change the method was static and $this was not used (see blame prior to that change).

Maybe you'd like to add a comment that this must be static since it is called by a hook

**Comment by mmattel** [comment] 2020-01-21 06:48
@micbar this should be fixed...

**Comment by VicDeo** [comment] 2020-01-21 08:41
> this must be static since it is called by a hook. 

it must NOT:
`public function loginName2UserName($param) {`
loginName2UserName is a non-static method so `$this` should be used.

This issue is 10.2-specific as 10.2.x loads wrong `app.php`  if there are two instances of `user_ldap` available. 
The workaround is to remove outdated `user_ldap` app from non-writable apps directory manually.

**Closed by VicDeo** 2020-01-21 08:41 UTC

**Comment by VicDeo** [comment] 2020-01-21 08:50
seems to be duplicate of https://github.com/owncloud/user_ldap/issues/447 btw
