### ISSUE TITLE
save button for ldap config

### ISSUE THREAD

**Issue by akurach** [owncloud/user_ldap#285] opened 2018-09-18 10:14 UTC
Hello, pls add save config button to config settings page. 
Got a lot of problems with autofill in the browser.

**Comment by voroyam** [comment] 2018-10-23 20:37
Thanks for the feedback. 

We are currently working on a new version of the config settings page.

**Comment by PVince81** [comment] 2018-12-03 21:54
new version in the works here https://github.com/owncloud/user_ldap/pull/210

**Comment by VicDeo** [comment] 2019-04-12 13:07
closing as a duplicate of https://github.com/owncloud/user_ldap/issues/27

**Closed** 2019-04-12 13:09 UTC
