### ISSUE TITLE
When using encryption, ldap users login for the first time have invalid private keys.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/user_ldap#177] opened 2018-02-05 11:58 UTC
### Steps to reproduce

1. Enable encryption.
2. Set up an ldap server - Do not run the user:sync command.
3. Login with an ldap user.

### Expected behaviour
User has new keys created and can use the server without any change required as any other user.

### Actual behaviour
The user gets a warning telling that his private keys are invalid.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.6.1","versionstring":"10.0.6","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes.

**Logs**

```
{"reqId":"lNA9RDe0Iiyln5CpBG3A","level":2,"time":"2018-02-05T11:39:13+00:00","remoteAddr":"HIDDEN_IP","user":"--","app":"OC\\User\\Manager","method":"POST","url":"\/index.php\/login","message":"User backend OCA\\User_LDAP\\User_Proxy provided no home for <b8e1702e-8742-1034-8cc0-39af73a96b9a>, using <\/opt\/owncloud\/data\/b8e1702e-8742-1034-8cc0-39af73a96b9a>."}
{"reqId":"lNA9RDe0Iiyln5CpBG3A","level":2,"time":"2018-02-05T11:39:16+00:00","remoteAddr":"HIDDEN_IP","user":"b8e1702e-8742-1034-8cc0-39af73a96b9a","app":"no app in context","method":"POST","url":"\/index.php\/login","message":"Could not decrypt the private key from user \"b8e1702e-8742-1034-8cc0-39af73a96b9a\"\" during login. Assume password change on the user back-end. Error message: Bad Signature"}
```

### Client configuration

**Browser**
N/A

**Comment by SergioBertolinSG** [comment] 2018-02-05 12:22
Working fine using server 10.0.1.

**Comment by SergioBertolinSG** [comment] 2018-02-05 12:32
It is not possible for the ldap users to set the private key after the first login:

```
{"reqId":"tLtY0XomiHC2y1sm6KkL","level":3,"time":"2018-02-05T12:29:52+00:00","remoteAddr":"HIDDEN_IP","user":"b8e1702e-8742-1034-8cc0-39af73a96b9a","app":"user_ldap","method":"POST","url":"\/index.php\/apps\/encryption\/ajax\/updatePrivateKeyPassword","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on ldap:\\\/\\\/LDAP_HOSTNAME:389\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(140): OCA\\\\User_LDAP\\\\User\\\\Manager->getLDAPUserByLoginName('b8e1702e-8742-1...')\\n#1 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(75): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(140): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('b8e1702e-8742-1...', 'checkPassword', Array)\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(180): OCA\\\\User_LDAP\\\\Proxy->handleRequest('b8e1702e-8742-1...', 'checkPassword', Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(221): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)\\n#6 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Controller\\\/SettingsController.php(113): OC\\\\User\\\\Manager->checkPassword(*** sensitive parameters replaced ***)\\n#7 [internal function]: OCA\\\\Encryption\\\\Controller\\\\SettingsController->updatePrivateKeyPassword(*** sensitive parameters replaced ***)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Encryption\\\\Controller\\\\SettingsController), 'updatePrivateKe...')\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Encryption\\\\Controller\\\\SettingsController), 'updatePrivateKe...')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('SettingsControl...', 'updatePrivateKe...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match('\\\/apps\\\/encryptio...')\\n#15 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/Manager.php\",\"Line\":528}"}
{"reqId":"tLtY0XomiHC2y1sm6KkL","level":2,"time":"2018-02-05T12:29:52+00:00","remoteAddr":"HIDDEN_IP","user":"b8e1702e-8742-1034-8cc0-39af73a96b9a","app":"core","method":"POST","url":"\/index.php\/apps\/encryption\/ajax\/updatePrivateKeyPassword","message":"Login failed: 'b8e1702e-8742-1034-8cc0-39af73a96b9a' (Remote IP: 'HIDDEN_IP')"}
```

**Comment by PVince81** [comment] 2018-02-05 15:17
Does it work after running user:sync ?

Since you say it worked in 10.0.1 there was likely a change, maybe in the order of how stuff is happening in core. Normally when an unknown LDAP user logs in it gets automatically synced (auto-provision). I'd expect the autoprovision to happen before this encryption key thing is happening.

@sharidas can you bisect this ?

**Comment by PVince81** [comment] 2018-02-05 15:32
@SergioBertolinSG can you test whether the problem still exists with https://github.com/owncloud/core/pull/30364 applied ?

**Comment by sharidas** [comment] 2018-02-06 07:44
Initially I thought the problem would be with core commit. During investigation with the core, I had to checkout `0.9.1` version of user_ldap, because minimum version required was 10.0.3 of core. The core version 10.0.1 and 10.0.2 are working. That process didn't helped me get the exact commit from the core. But it helped me realise that issue is around user_ldap repo. So started bisecting from the master branch to `0.9.1`. And found the commit which was breaking with core master branch. The user_ldap commit : https://github.com/owncloud/user_ldap/commit/aa84b18f85fca05465bd7c6f7d362b60e3527915 is causing this issue. If I checkout commit https://github.com/owncloud/user_ldap/commit/61b25bae08e59a885f351dafb462c173140d23d9 it was working, which is the commit before  https://github.com/owncloud/user_ldap/commit/aa84b18f85fca05465bd7c6f7d362b60e3527915

**Comment by butonic** [comment] 2018-02-06 09:35
Logic might change again with https://github.com/owncloud/core/pull/29669 Investigating

**Comment by butonic** [comment] 2018-02-06 10:04
Reproduced with master. On it

**Comment by butonic** [comment] 2018-02-06 10:26
fixed with https://github.com/owncloud/user_ldap/pull/156 ... rebasing and polishing it

**Comment by butonic** [comment] 2018-02-06 10:38
#156 depends on core doing the sync
https://github.com/owncloud/user_ldap/pull/178 fixes this now.

**Closed** 2018-02-08 09:19 UTC
Labels: bug, p1-urgent, regression, sev1-critical
