### ISSUE TITLE
occ commands throw an exception after upgrading to user_ldap-0.14.0RC1 from an older version

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#447] opened 2019-08-06 12:18 UTC
### Steps to reproduce

1. Install an oC server using LDAP 0.13.0
2. Log in with an ldap user (checks LDAP works)
3. Via CLI run upgrade ```occ market:install -l user_ldap-0.14.0RC1.tar.gz``` 
4. Run occ app:list command

### Expected behaviour

occ commands should work after the user_ldap upgrade

### Actual behaviour

occ commands fails:

![Screen Shot 2019-08-06 at 10 57 15](https://user-images.githubusercontent.com/10596560/62539080-a8c8b400-b854-11e9-891f-a94543903086.png)

**Note:** Using user_ldap-0.14.0RC1 from scratch (fresh installation) works fine and occ commands are available.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7.2.16-1+ubuntu16.04

**ownCloud version:**

"version":""10.2.1.4" EE"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using encryption:** 
No

**Logs**

No Server Logs spotted

```
```

(cc @patrickjahns jfyi)

**Comment by patrickjahns** [comment] 2019-08-06 12:46
Different szenario which works

- Install owncloud https://download.owncloud.org/community/owncloud-10.2.1.tar.bz2 
- Download userldap from https://github.com/owncloud/user_ldap/releases/tag/v0.14.0RC1
- `occ m:i -l user_ldap-0.14.0RC1.tar.gz`

Everything works

**Comment by patrickjahns** [comment] 2019-08-06 12:52
Following szenario fails:

- Install owncloud https://download.owncloud.org/community/owncloud-10.2.1.tar.bz2
- Dowload userldap v0.13.0 from https://github.com/owncloud/user_ldap/releases/tag/v0.13.0
- extract contents to `apps/user_ldap`
- `occ app:enable user_ldap`
- Download userldap v0.14.0RC1 from https://github.com/owncloud/user_ldap/releases/tag/v0.14.0RC1
- occ m:i -l user_ldap-0.14.0RC1.tar.gz

Which means we are currently having issues with `apps` and `apps-external`

**Comment by VicDeo** [comment] 2019-08-15 14:54
introduced by https://github.com/owncloud/user_ldap/commit/360af338bf93bb87a473144a53703ca1e2ff2bc2#diff-224bb875c5d3cfcd7621135069013242

Hotfix will be to restore the file `appinfo/register_command.php` and remove the line `<command>OCA\User_LDAP\Command\CheckUser</command>` from info.xml

But I want to know what is going on there.

**Comment by DeepDiver1975** [comment] 2019-08-16 06:58
The issue is that user_ldap is installed in two different places - this will never work!

The only option we have is to detect this situation and bail out with an error.
The operator has the two options: live with the old app version or manually delete the old version and install the new version via the marketplace.

**Comment by VicDeo** [comment] 2019-08-16 15:36
огые as I thought it's a core thing related to a wrong `appinfo/app.php` loaded in https://github.com/owncloud/core/blob/master/lib/private/legacy/app.php#L239

**Comment by VicDeo** [comment] 2019-08-16 16:26
@patrickjahns @davitol here you go 
https://github.com/owncloud/core/pull/36054

**Comment by VicDeo** [comment] 2019-08-18 15:40
@DeepDiver1975 configuration with the same app in two app directories has been supported so far and should load the newest version.

**Comment by VicDeo** [comment] 2019-08-19 11:39
@patrickjahns 
it's a core bug but if we want to keep 10.2 compatibility in this release we need to made changes that I suggested in https://github.com/owncloud/user_ldap/issues/447#issuecomment-521670744

otherwise this user_ldap release can be only 10.3 compatible

**Comment by VicDeo** [comment] 2019-08-19 13:34
core fix: https://github.com/owncloud/core/pull/36054
additionally if 0.14 should be 10.2+ compatible we need   https://github.com/owncloud/user_ldap/pull/449 for user_ldap

**Comment by PVince81** [comment] 2019-08-20 12:47
core fix merged.

I don't think we need a hotfix here (especially not one that reverts back to much older code), unless people are really stuck on 10.2 and have troubles updating to 10.3

**Closed by PVince81** 2019-08-20 12:47 UTC
Labels: QA-blocker, QA-team
