### ISSUE TITLE
[QA] tab break into new line hides content

### ISSUE THREAD

**Issue by mmattel** [owncloud/user_ldap#656] opened 2021-07-07 06:30 UTC
Opera, Chrome, FF

If force reloading the screen, this looks like that 💥 

![image](https://user-images.githubusercontent.com/3321281/124710361-f34d8200-defc-11eb-86d7-b3e41de7c22e.png)

But if resizing the screen it changes to the correct view :white_check_mark: 

![image](https://user-images.githubusercontent.com/3321281/124710500-2b54c500-defd-11eb-9994-9fb11cf392d9.png)

@jnweiger needs to be added to the defect list in #605

@JanAckermann @hurradieweltgehtunter mind to take a look if you can fix this?

**Comment by mmattel** [comment] 2021-07-07 08:41
@hurradieweltgehtunter thanks a lot

**Comment by mmattel** [comment] 2021-07-07 13:52
@hurradieweltgehtunter has the commit be merged? I cant find it or I am just blind...
If merged, we can close the issue.

**Comment by JanAckermann** [comment] 2021-07-07 14:53
@mmattel the commits are in the release branch: https://github.com/owncloud/user_ldap/commits/release-0.15.3
they will be back-merged into the master branch after release

**Comment by jnweiger** [comment] 2021-07-07 16:19
Tested in 0.15.4-rc1:

* The tabs now scroll with the contents. Is that intended?
![image](https://user-images.githubusercontent.com/1108546/124794336-2f113780-df4f-11eb-843b-2140c9430c1d.png)

* The "Configuration OK" message is see twice, top and bottom.
![image](https://user-images.githubusercontent.com/1108546/124794429-4cde9c80-df4f-11eb-9cc5-42dcf081e038.png)

* when there is little horizontal space, the "Configuration OK" jump into the heading, and looses the server information:
![image](https://user-images.githubusercontent.com/1108546/124794503-641d8a00-df4f-11eb-8f6a-79a238e74f54.png)

@hurradieweltgehtunter That seems to revert parts if the initial facelift. (e.g. Fixed top bar)

**Comment by hurradieweltgehtunter** [comment] 2021-07-08 07:15
Yes it reverts parts of it but this is intended/forced. 
I fixed the third issue you mentioned in `release-0.15.3`

**Comment by jnweiger** [comment] 2021-07-13 11:05
Retested in 0.15.4-RC2

* Can no longer reproduce Martin's origina lissue here. No overlaps. The contents properly jumps down, when the tabs wrap.
* the tabs row scrolls up with the content
* proper whitespace aorond the green ball.

**Closed by jnweiger** 2021-07-13 11:05 UTC
