### ISSUE TITLE
LDAP internal username attributes wrongly loaded into the oc_accounts table

### ISSUE THREAD

**Issue by pako81** [owncloud/user_ldap#118] opened 2017-07-27 11:00 UTC
oC 10.0.2

Having the following configured in LDAP:

```
| ldapExpertUUIDGroupAttr |       |
| ldapExpertUUIDUserAttr  | goeId |
| ldapExpertUsernameAttr  | goeId |
```

The single-user import works:

```
root@owncloud-dev-1:/var/www/owncloud# sudo -u www-data ./occ user:sync -vvv -u 'user@example.com' -m disable "OCA\User_LDAP\User_Proxy"
Insert new and update existing users ...
Syncing user@example.com: created 
{"id":238145,"backend":"OCA\\User_LDAP\\User_Proxy","userId":"user@example.com","displayName":"user@example.com","email":null,"home":"\/mnt\/oc_stor_userdata\/0437819","lastLogin":0,"quota":null} 
(0.013389110565186)
```

But then in the `oc_accounts` table it looks like the `user_id` and `lower_user_id` are being wrongly set:

```
mysql> SELECT * FROM oc_accounts where id = "238145";
+--------+-------+-------------------+-------------------+-------------------+-------+------------+--------------------------+-------------------------------+-------+
| id     | email | user_id           | lower_user_id     | display_name      | quota | last_login | backend                  | home                          | state |
+--------+-------+-------------------+-------------------+-------------------+-------+------------+--------------------------+-------------------------------+-------+
| 238145 | NULL  | user@example.com  | user@example.com  | user@example.com  | NULL  | 0          | OCA\User_LDAP\User_Proxy | /mnt/oc_stor_userdata/0437819 | 1     |
+--------+-------+-------------------+-------------------+-------------------+-------+------------+--------------------------+-------------------------------+-------+
1 row in set (0.00 sec)
```
`email` and `quota` are wrongly imported as well.

This makes login for this LDAP user not possible.

@jvillafanez @tomneedham FYI

@jvillafanez please have a look at https://github.com/owncloud/enterprise/issues/2177#issuecomment-318309300 for more info.

**Comment by tomneedham** [comment] 2017-07-27 12:09
I hope it wasnt caused by this: https://github.com/owncloud/user_ldap/commit/cc693f37d70aee77ff7b78167160d5c6eadf5005

**Comment by jvillafanez** [comment] 2017-08-09 16:14
Looks like the error is caused by https://github.com/owncloud/core/pull/28212

**Comment by tomneedham** [comment] 2017-08-14 11:19
@PVince81 @butonic 10.0.3 critical?

**Comment by tomneedham** [comment] 2017-08-14 11:20
(only caused when using above LDAP PR for single user sync, which IMO should be in 10.0.3 as its very very useful for big instances)

**Comment by butonic** [comment] 2017-08-14 11:56
@jvillafanez I think this is caused by https://github.com/owncloud/user_ldap/pull/109 maybe interferes with https://github.com/owncloud/core/pull/28212

**Comment by butonic** [comment] 2017-08-14 11:56
I need to rework this anyway. Today or tomorrow...

**Comment by jvillafanez** [comment] 2017-08-14 12:16
Check also https://github.com/owncloud/enterprise/issues/2177#issuecomment-318633928 since the user_id isn't right.

**Comment by PVince81** [comment] 2017-08-15 14:08
@tom @butonic so p1 then ?

**Comment by butonic** [comment] 2017-08-15 15:22
Yes

**Comment by tomneedham** [comment] 2017-11-13 09:08
Moving to planned since this is related to the single user sync which is a core PR which is still open and in development

**Closed** 2017-11-13 09:15 UTC
Labels: 1 - To develop, blue-ticket, p1-urgent, sev2-high
