### ISSUE TITLE
2 LDAP servers configured occ user:sync "OCA\User_LDAP\User_Proxy" command request to both backends at the same time

### ISSUE THREAD

**Issue by davitol** [owncloud/user_ldap#94] opened 2017-05-08 12:33 UTC
### Steps to reproduce

1. Set 2 LDAP configurations in the wizard (1200 users + 225 users)  with  Paging chunksize set to 500
2. Run ```sudo -u www-data ./occ user:sync "OCA\User_LDAP\User_Proxy"```

### Expected behaviour

The chucksize should be 500 

### Actual behaviour

```sudo -u www-data ./occ user:sync "OCA\User_LDAP\User_Proxy"``` command is taking 725 as chucksize (500 + 225) . So both request seems to be running at the same time.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.12"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDAV

**Are you using encryption:** 
No

**Logs**

Server Logs

```

```

### Client configuration

**Browser**

Mozilla

![screen shot 2017-05-08 at 14 16 52](https://cloud.githubusercontent.com/assets/10596560/25804222/eb943100-33fa-11e7-84d0-1035e5b679d1.png)

@jvillafanez

**Comment by butonic** [comment] 2017-05-16 18:30
The queries to ldap use a chunksize of 500. 725 = 500 + 225 (all users from the second ldap) That is also what I would expect. RAM usage may increase because multiples of 500 users may be in ram. Did this lead to any problems when syncing?

**Comment by davitol** [comment] 2017-05-17 08:04
The sync command got stucked for a while when I synced lot of users, but probably it is not related. Without more info I feel OK about set sev-3 and discuss about it in the future.

**Comment by butonic** [comment] 2017-11-17 07:04
stuck as in slow caused by horrible old sync implementation. rewritten and fixed with https://github.com/owncloud/user_ldap/pull/125

**Closed by butonic** 2017-11-17 07:04 UTC
Labels: bug, sev3-medium
